Repository wooga/atlas-version, pull requests merged in 2022-05, with the labels that each got.

#48 Update net.wooga.plugins to version 3.x [ATLAS-728]
  build.gradle
  settings.gradle
  src/main/resources/META-INF/gradle-plugins/net.wooga.version.properties
Labels: change, atlas-stream, update, improve

#49 Add a way to set the version by string by script, property or environ…
  src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
  src/main/groovy/wooga/gradle/version/VersionPluginConventions.groovy
  src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
  src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
Labels: atlas-stream, add

#46 Previous version property is null when there isn't any version tag on git
  src/main/groovy/wooga/gradle/version/internal/release/semver/NearestVersion.groovy
  src/main/groovy/wooga/gradle/version/internal/release/semver/NearestVersionLocator.groovy
  src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
  src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
Labels: atlas-stream, improve
