Repository wooga/atlas-version, pull requests merged in 2022-03, with the labels that each got.

#38 Refactor project using gradle-commons
  build.gradle
  src/main/groovy/wooga/gradle/version/VersionPlugin.groovy
  src/main/groovy/wooga/gradle/version/VersionPluginConventions.groovy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
Labels: atlas-stream, improve

#39 Refactors the implementation of base properties in the default extens…
  src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
Labels: atlas-stream, update

#37 Add helper methods to get the release stage
  build.gradle
  src/integrationTest/groovy/wooga/gradle/version/IntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/version/VersionIntegrationSpec.groovy
  src/integrationTest/groovy/wooga/gradle/version/VersionPluginIntegrationSpec.groovy
  src/main/groovy/wooga/gradle/version/ReleaseStage.groovy
  src/main/groovy/wooga/gradle/version/VersionPluginConventions.groovy
  src/main/groovy/wooga/gradle/version/VersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/internal/release/base/VersionStrategy.groovy
  src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
  src/main/groovy/wooga/gradle/version/internal/release/semver/SemVerStrategy.groovy
  src/main/groovy/wooga/gradle/version/strategies/SemverV2Strategies.groovy
Labels: atlas-stream, add

#40 Add a "preflight" release stage [ATLAS-646]
  src/main/groovy/wooga/gradle/version/ReleaseStage.groovy
  src/main/groovy/wooga/gradle/version/VersionScheme.groovy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
  src/main/groovy/wooga/gradle/version/strategies/SemverV1Strategies.groovy
  src/main/groovy/wooga/gradle/version/strategies/WdkStrategies.groovy
  src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
Labels: atlas-stream, add

#41 Update to latest 2x plugins plugin
  build.gradle
Labels: atlas-stream, update

#42 Add prefight release stage
  src/main/groovy/wooga/gradle/version/ReleaseStage.groovy
  src/main/groovy/wooga/gradle/version/VersionScheme.groovy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/internal/release/opinion/Strategies.groovy
  src/main/groovy/wooga/gradle/version/strategies/SemverV1Strategies.groovy
  src/main/groovy/wooga/gradle/version/strategies/WdkStrategies.groovy
  src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
Labels: atlas-stream, add

#43 Add missing value to the set of possible value mappigns for PREFLGIHT…
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/strategies/WdkStrategies.groovy
Labels: atlas-stream, add

#44 Add preflight version support in staticMarker strategy
  src/main/groovy/wooga/gradle/version/internal/DefaultVersionPluginExtension.groovy
  src/main/groovy/wooga/gradle/version/strategies/SemverV2Strategies.groovy
  src/main/groovy/wooga/gradle/version/strategies/StaticMarkerStrategies.groovy
  src/test/groovy/wooga/gradle/version/VersionPluginSpec.groovy
Labels: atlas-stream, fix, add
